[build]
  # Build command to run Vite (assuming you're using npm or yarn)
  command = "npm run build"  # Or "yarn build" if you're using yarn

  # The directory where Netlify will find the compiled assets
  publish = "public"  # Make sure this is the location of your built assets (Laravel's 'public' folder)

[context.production.environment]
  # Laravel environment variables that will be needed during the deployment
  APP_NAME = "Laravel"
  APP_ENV = "production"
  APP_KEY = "base64:your-generated-app-key"  # Set your generated APP_KEY here
  APP_DEBUG = "false"
  APP_URL = "https://your-netlify-site-url.netlify.app"
  
  # TailwindCSS, Vite, and Pusher (optional) environment variables
  VITE_PUSHER_APP_KEY = "your-pusher-app-key"  # Optional, only if using Pusher for real-time features
  VITE_PUSHER_HOST = "your-pusher-host"        # Optional
  VITE_PUSHER_PORT = "443"                     # Optional
  VITE_PUSHER_SCHEME = "https"                 # Optional
  VITE_PUSHER_APP_CLUSTER = "mt1"              # Optional
